spring:
  application:
    name: project
  profiles: prod
  jpa:
    hibernate:
      ddl-auto: update
    debug: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    continue-on-error: true
    url: jdbc:mysql://ip:port/aquarius?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: username
    password: password


server:
  port: 8080

swagger2:
  enable: true